FROM ubuntu:22.04

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and Node.js (add Node.js PPA to ensure latest version)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    openjdk-21-jdk \
    g++ \
    build-essential \
    make \
    git \
    sudo \
    pkg-config \
    libsystemd-dev \
    libcap-dev \
    curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean -y && \
    apt-get remove -y --auto-remove && \
    apt-get remove -y --purge && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/* /tmp/*


WORKDIR /app

# Clone and install isolate
COPY packages/jobs/install-isolate.sh .
RUN chmod +x install-isolate.sh && ./install-isolate.sh

# Enable corepack for pnpm / yarn
RUN corepack enable

# Copy only dependency files first (better caching)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/
COPY packages/api/package.json packages/api/
COPY packages/auth/package.json packages/auth/
COPY packages/db/package.json packages/db/
COPY packages/jobs/package.json packages/jobs/
COPY packages/validators/package.json packages/validators/
COPY tooling/eslint/package.json tooling/eslint/
COPY tooling/github/package.json tooling/github/
COPY tooling/prettier/package.json tooling/prettier/
COPY tooling/tailwind/package.json tooling/tailwind/
COPY tooling/typescript/package.json tooling/typescript/


# Install deps
RUN pnpm install

# Copy the rest of the repo
COPY . .

# Expose common dev ports (adjust as needed)
EXPOSE 3000 

CMD ["pnpm", "dev"]

